[build]
command = "npm run build"
publish = "build/client"

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"
[headers.values]
  "Cache-Control" = "public, max-age=31560000, immutable"

# Add the Content-Security-Policy header for all HTML pages, allowing Brevo scripts and resources.
[[headers]]
for = "/*"
[headers.values]
  Content-Security-Policy = "script-src 'self' https://cdn.brevo.com; connect-src 'self' https://cdn.brevo.com;"